// Generated by CoffeeScript 1.7.1
(function() {
  this.MoleGame = this.MoleGame || {};

  this.MoleGame.Boot = function() {};

  this.MoleGame.Boot.prototype = {
    preload: function() {
      return this.load.pack('preload', 'assets/assets.json');
    },
    create: function() {
      this.stage.backgroundColor = '#000';
      this.stage.forcePortrait = false;
      this.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
      this.scale.minWidth = 240;
      this.scale.minHeigh = 170;
      this.scale.maxWidth = 2880;
      this.scale.maxHeight = 1920;
      this.scale.pageAlignHorizontally = true;
      this.scale.pageAlignVertically = true;
      this.scale.setScreenSize(true);
      this.input.maxPointers = 1;
      this.input.addPointer();
      return this.state.start('Preload');
    }
  };

}).call(this);

//# sourceMappingURL=boot.map
