// Generated by CoffeeScript 1.7.1
(function() {
  this.MoleGame = this.MoleGame || {};

  this.MoleGame.game = new Phaser.Game(1024, 768, Phaser.AUTO, '');

  this.MoleGame.game.state.add('Boot', this.MoleGame.Boot);

  this.MoleGame.game.state.add('Preload', this.MoleGame.Preload);

  this.MoleGame.game.state.start('Boot');

}).call(this);

//# sourceMappingURL=main.map
