// Generated by CoffeeScript 1.7.1
(function() {
  this.MoleGame = this.MoleGame || {};

  this.MoleGame.Preload = function() {};

  this.MoleGame.Preload.prototype = {
    preload: function() {
      this.preloadBg = this.add.sprite(this.world.centerX, this.world.centerY, 'preloadBg');
      this.preloadBg.anchor.set(.5);
      this.preloadProgress = this.add.sprite(this.world.centerX, this.world.centerY, 'preloadProgress');
      this.preloadProgress.anchor.set(.5);
      this.percentText = this.add.bitmapText(this.world.centerX - 45, this.world.centerY - 80, 'coFont', '', 24);
      this.load.setPreloadSprite(this.preloadProgress);
      this.load.crossOrigin = true;
      this.load.onFileComplete.add(this.showPercent, this);
      this.load.pack('mainMenu', 'assets/assets.json');
      return this.load.pack('game', 'assets/assets.json');
    },
    showPercent: function(progress) {
      return this.percentText.setText("" + progress + "%");
    }
  };

}).call(this);

//# sourceMappingURL=preload.map
